# Problemas 12-11 y 12-89

In [1]:
import pandas as pd
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
df = pd.read_excel('table 12-3.xlsx')
df['nv'] = df['n/v']
df.head()

,mfr,carline,cartruck,cid,rhp,trns,drv,od,etw,cmp,axle,n/v,a/c,hc,co,co2,mpg,nv
0,20,300C/SRT-8,C,215,253,L5,4,2,4500,9.9,3.07,30.9,Y,0.011,0.09,288,30.8,30.9
1,20,CARAVAN2WD,T,201,180,L4,F,2,4500,9.3,2.49,32.3,Y,0.014,0.11,274,32.5,32.3
2,20,CROSSFIREROADSTER,C,196,168,L5,R,2,3375,10.0,3.27,37.1,Y,0.001,0.02,250,35.4,37.1
3,20,DAKOTAPICKUP2WD,T,226,210,L4,R,2,4500,9.2,3.55,29.6,Y,0.012,0.04,316,28.1,29.6
4,20,DAKOTAPICKUP4WD,T,226,210,L4,4,2,5000,9.2,3.55,29.6,Y,0.011,0.05,365,24.4,29.6

In [3]:
modelo = smf.ols('mpg ~ cid + rhp + etw + cmp + axle + nv + C(trns)', data=df)
resultado = modelo.fit()
resultado.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.911
Model:                            OLS   Adj. R-squared:                  0.852
Method:                 Least Squares   F-statistic:                     15.38
Date:                Thu, 09 Nov 2017   Prob (F-statistic):           3.26e-05
Time:                        15:10:29   Log-Likelihood:                -40.441
No. Observations:                  21   AIC:                             98.88
Df Residuals:                      12   BIC:                             108.3
Df Model:                           8
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        40.1560     21.300      1.885      0.084      -6.253      86.566
C(trns)[T.L5]     0.2290      1.519      0.151      0.883      -3.082       3.540
C(trns)[T.M6]    -3.0605      2.479     -1.235      0.241      -8.462       2.340
cid              -0.0012      0.028     -0.044      0.965      -0.062       0.059
rhp               0.0009      0.017      0.051      0.960      -0.036       0.038
etw              -0.0041      0.001     -3.749      0.003      -0.006      -0.002
cmp               0.6537      1.755      0.373      0.716      -3.169       4.477
axle             -2.5755      1.606     -1.604      0.135      -6.075       0.924
nv                0.3060      0.304      1.005      0.335      -0.357       0.969
==============================================================================
Omnibus:                        5.036   Durbin-Watson:                   1.873
Prob(Omnibus):                  0.081   Jarque-Bera (JB):                3.370
Skew:                          -0.391   Prob(JB):                        0.185
Kurtosis:                       4.800   Cond. No.                     1.97e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.97e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [4]:
predic = resultado.get_prediction(exog={'cid': 215,
                                        'rhp': 253,
                                        'etw': 4500,
                                        'cmp': 9.9,
                                        'axle': 3.07,
                                        'nv': 30.9,
                                        'trns': 'M6'})

In [5]:
predic.summary_frame()

,mean,mean_se,mean_ci_lower,mean_ci_upper,obs_ci_lower,obs_ci_upper
0,26.655669,2.850189,20.445641,32.865697,18.816151,34.495187